sudo: required
language: node_js
node_js:
  - "6"
matrix:
  fast_finish: true
before_install:
  - npm i npm@^4 -g
install:
  - npm install
script:
  - npm run ci
cache:
  directories:
    - node_modules
addons:
  sauce_connect: true
  code_climate:
    repo_token: 5158cdccb838275ebc3c84594a1b1cff8dba5626effdfe41d055d203a34ec1de
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start 
