sudo: required
language: node_js
node_js:
  - "6"
matrix:
  fast_finish: true
before_install:
  - npm i npm@^4 -g
install:
  - npm install
script:
  - npm run ci
cache:
  directories:
    - node_modules
addons:
  sauce_connect: true
  apt:
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  