sudo: required
language: node_js
node_js:
  - "6"
matrix:
  fast_finish: true
before_install:
  - npm i npm@^4 -g
install:
  - npm install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run e2e
cache:
  directories:
    - node_modules
addons:
  sauce_connect: true
  